### ISSUE TITLE
Google Chrome for Android show a new download button in fullscreen mode

### ISSUE THREAD

**Issue by rubenrua** [polimediaupv/paella#232]
![fullscreen](https://cloud.githubusercontent.com/assets/195745/23065757/78154ae2-f517-11e6-902f-1c2aa98b89cf.png)

Fixed with:
```css
video::-internal-media-controls-download-button {
    display:none;
}

video::-webkit-media-controls-enclosure {
    overflow:hidden;
}

video::-webkit-media-controls-panel {
    width: calc(100% + 30px); /* Adjust as needed */
}
```

More info: 

* http://stackoverflow.com/questions/41115801/in-chrome-55-prevent-showing-download-button-for-html-5-video
* http://stackoverflow.com/questions/39602852/disable-download-button-for-google-chrome/40975859#40975859
